# Site settings
title: Máximo Oliveira
baseurl: ""
url: "maximooliveira.com"

# Author
author:
  name: Máximo Oliveira
  desc: Hello nice to meet you
  email: esa.maximoliveira@gmail.com
  selfie: "assets/img/profile.png"

# social
social:
  email: true
  behance:
  github: MaximoOliveira
  instagram:
  keybase:
  linkedin: https://www.linkedin.com/in/m%C3%A1ximo-oliveira-979b44173/
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"
