# Site settings
title:          Maximo Oliveira
description:    "Minimal Jekyll theme for storytellers"
baseurl:        ""
url: "https://maximooliveira.com/"

# Google Analytics
google_analytics: G-B5NMFWQ9QW

# Author
author:
  name:         Maximo Oliveira
  url:          https://maximooliveira.com/

# social
social:
  github: MaximoOliveira
  linkedin: https://www.linkedin.com/in/m%C3%A1ximo-oliveira-979b44173/
  default_txt: "Follow On"

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

